[package]
name = "rat-music"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ratatui = "0.23.0"
rodio = "0.17.2"
tokio = "1.33.0"
