[package]
name = "rat-music"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
crossterm = "0.27.0"
id3 = "1.9.0"
ratatui = "0.23.0"
rfd = "0.12.1"
rodio = "0.17.2"
